---

- name: Install Apache
  become: yes
  apt: pkg=apache2 state=latest update_cache=yes

- name: Install Apache Modules
  command: a2enmod {{item}} creates="/etc/apache2/mods-enabled/{{item}}.load"
  with_items: "{{ apache_modules }}"

- name: disabling default site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
