---

- name: Install apache2 shibboleth module
  become: yes
  apt: name=libapache2-mod-shib2
       state=installed

- name: Ensure /var/run/shibboleth exists
  file: name=/var/run/shibboleth state=directory
